spring.application.name=file-upload-adaptor
server.port=8081

#Database sql configuration
spring.datasource.url=jdbc:mysql://localhost:3306/file_processing
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

#Logs Configuration
logging.base.path=C:/Users/Nihal Varma/Desktop/My Projects/logs
track.name=Asynchronous-File-Processing-System
interface.name=file-upload-adaptor
logging.config=classpath:logback-spring.xml
logging.file.name=${logging.base.path}/${track.name}/${interface.name}/${interface.name}.log
logging.level.root=info
logging.level.com.myproject=TRACE
logging.level.com.zaxxer.hikari.pool.HikariPool=INFO
logging.level.org.springframework.ws.client=TRACE

#Kafka Configuration
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

file.upload-dir=C:/Users/Nihal Varma/Desktop/My Projects/Asynchronous-File-Processing-System/Input_Files

