spring.application.name=file-upload-adaptor
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/file_processing
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092

file.upload-dir=C:\\Users\\Nihal Varma\\Desktop\\My Projects\\Asynchronous-File-Processing-System\\Input_Files
