spring.application.name=email-trigger-service

server.port=${SERVER_PORT}
server.servlet.context-path=${APP_CONTEXT_PATH}

track.name=CLAIMS
interface.name=monthly-claims-email-autotrigger

application.timeZone=${TARGET_TIMEZONE:UTC}

#log
logging.base.path=${LOGS_ROOT_FOLDER}/
logging.config=classpath:logback-spring.xml
logging.file.name=${logging.base.path}/${track.name}/${interface.name}/${interface.name}.log
logging.level.root=info
logging.level.com.usthealthproof=trace
logging.level.com.zaxxer.hikari.pool.HikariPool=info
logging.level.org.springframework.ws.client=trace


# SMTP Configuration
spring.mail.host=${SMTP_MAIL_HOST}
spring.mail.port=${SMTP_MAIL_PORT}

# SMTP Properties
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

file.upload.path=${MONTHLY_CLAIMS_REPORT_PATH}

mail.to= ${RECIPIENT_EMAIL_LIST}
